// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tracinpbdiobiamnwzhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyYWNpbnBiZGlvYmlhbW53emh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTM4MDUsImV4cCI6MjA2MzI4OTgwNX0._FcoKfD-pynlXCRsIIgMoccnATi8ElrdoDLzMDHVCII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);